name: ci

on:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Windows setup chocolatey package manager
        if: matrix.os == 'windows-2022'
        uses: crazy-max/ghaction-chocolatey@v2

      - name: Windows setup tools
        run: choco install cmake llvm pip ninja

      - name: Linux setup tools
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get install cmake llvm pip ninja-build

      - name: Install conan package manager
        run: pip install conan

      - name: Detect conan profile
        run: conan profile detect

      - name: Install conan packages
        run: conan install . --output-folder=build-rel

      - name: CMake config
        run: cmake -S . -B build-rel -G Ninja -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: CMake build
        run: cmake --build build-rel

      - name: CPack project
        if: startsWith(github.ref, 'refs/tags')
        working-directory: build-rel
        run: cpack -G ZIP --config CPackConfig.cmake

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: build-rel/*.zip

    