name: ci

on:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
        windowing-system:
          - glfw3

    steps:
      - uses: actions/checkout@v3

      - name: Windows setup tools
        if: matrix.os == 'windows-2022'
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install cmake llvm ninja

      - name: Linux setup tools
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get install cmake pip libgl-dev pkg-config libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-util-dev libxcb-util0-dev uuid-dev libxcb-cursor-dev libegl-dev libegl1-mesa-dev

      - name: Install conan package manager
        run: pip install conan

      - name: Detect conan profile
        run: conan profile detect

      - name: Install conan packages
        uses: ./.github/actions/install_conan_packages
        with:
          os: ${{ matrix.os }}
          windowing-system: ${{ matrix.windowing-system }}

      - name: CMake config
        uses: ./.github/actions/cmake_config
        with:
          os: ${{ matrix.os }}
          windowing-system: ${{ matrix.windowing-system }}

      - name: CMake build
        run: cmake --build build-rel

      - name: CPack project
        if: startsWith(github.ref, 'refs/tags')
        working-directory: build-rel
        run: cpack -G ZIP --config CPackConfig.cmake

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: build-rel/*.zip

    